-- Generated by wallust. Do not edit; edit the template instead:
--   ~/.config/wallust/templates/colors-hypr.lua
-- Consumed by ~/.config/hypr/theme.lua

return {
    background = "rgb(020709)",
    foreground = "rgb(F1DAE3)",
    cursor     = "rgb(F1DAE3)",
    color0     = "rgb(02080B)",
    color1     = "rgb(3F484F)",
    color2     = "rgb(454D58)",
    color3     = "rgb(535E70)",
    color4     = "rgb(5C6A7C)",
    color5     = "rgb(687889)",
    color6     = "rgb(697B8D)",
    color7     = "rgb(F1DAE3)",
    color8     = "rgb(1C2021)",
    color9     = "rgb(455260)",
    color10    = "rgb(4D5D6F)",
    color11    = "rgb(677B99)",
    color12    = "rgb(607EA3)",
    color13    = "rgb(6B90B7)",
    color14    = "rgb(8DB3D9)",
    color15    = "rgb(F1DAE3)",
}
