local M = {}

function M.apply(p)
  local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  -- =========================================================================
  -- 1. Editor UI Core
  -- =========================================================================
  hl("Normal", { fg = p.fg, bg = p.bg })
  hl("NormalNC", { fg = p.fg_dim, bg = p.bg })
  hl("NormalFloat", { fg = p.fg, bg = p.bg_layer1 })
  hl("FloatBorder", { fg = p.line, bg = p.bg_layer1 })
  hl("FloatTitle", { fg = p.accent, bg = p.bg_layer1, bold = true })

  hl("Cursor", { fg = p.bg_solid, bg = p.accent })
  hl("CursorLine", { bg = p.bg_layer1 })
  hl("CursorLineNr", { fg = p.accent, bold = true })
  hl("LineNr", { fg = p.dim })
  hl("SignColumn", { fg = p.dim, bg = p.bg })
  hl("FoldColumn", { fg = p.dim, bg = p.bg })
  hl("Folded", { fg = p.dim, bg = p.bg_layer1 })

  hl("VertSplit", { fg = p.line_dim, bg = p.bg })
  hl("WinSeparator", { fg = p.line, bg = p.bg })
  hl("StatusLine", { fg = p.fg, bg = p.bg_layer1 })
  hl("StatusLineNC", { fg = p.dim, bg = p.bg_layer1 })

  hl("TabLine", { fg = p.dim, bg = p.bg_layer1 })
  hl("TabLineSel", { fg = p.accent, bg = p.bg_layer2, bold = true })
  hl("TabLineFill", { bg = p.bg_layer1 })

  hl("Pmenu", { fg = p.fg, bg = p.bg_layer1 })
  hl("PmenuSel", { fg = p.on_accent, bg = p.accent, bold = true })
  hl("PmenuSbar", { bg = p.bg_layer2 })
  hl("PmenuThumb", { bg = p.line })
  hl("PmenuBorder", { fg = p.line, bg = p.bg_layer1 })

  hl("Visual", { fg = p.sel_fg, bg = p.sel_bg })
  hl("VisualNOS", { fg = p.sel_fg, bg = p.sel_bg })
  hl("Search", { fg = p.on_accent, bg = p.accent_dim })
  hl("IncSearch", { fg = p.on_accent, bg = p.accent, bold = true })
  hl("CurSearch", { fg = p.on_accent, bg = p.accent, bold = true })
  hl("MatchParen", { fg = p.accent, bold = true, underline = true })

  hl("ColorColumn", { bg = p.bg_layer1 })
  hl("Conceal", { fg = p.dim })
  hl("Directory", { fg = p.accent })
  hl("Title", { fg = p.accent, bold = true })
  hl("NonText", { fg = p.dim })
  hl("SpecialKey", { fg = p.dim })
  hl("Question", { fg = p.accent })
  hl("MoreMsg", { fg = p.ok })
  hl("ModeMsg", { fg = p.fg, bold = true })
  hl("ErrorMsg", { fg = p.alert, bold = true })
  hl("WarningMsg", { fg = p.warn, bold = true })
  hl("WildMenu", { fg = p.on_accent, bg = p.accent })

  -- =========================================================================
  -- 2. Standard Syntax
  -- =========================================================================
  hl("Comment", { fg = p.comment, italic = true })
  hl("Constant", { fg = p.constant })
  hl("String", { fg = p.string })
  hl("Character", { fg = p.string })
  hl("Number", { fg = p.number })
  hl("Boolean", { fg = p.boolean, bold = true })
  hl("Float", { fg = p.number })
  hl("Identifier", { fg = p.fg })
  hl("Function", { fg = p.func, bold = true })
  hl("Statement", { fg = p.keyword, bold = true })
  hl("Conditional", { fg = p.keyword, bold = true })
  hl("Repeat", { fg = p.keyword, bold = true })
  hl("Label", { fg = p.keyword })
  hl("Operator", { fg = p.operator })
  hl("Keyword", { fg = p.keyword, bold = true })
  hl("Exception", { fg = p.alert, bold = true })
  hl("PreProc", { fg = p.accent2 })
  hl("Include", { fg = p.keyword })
  hl("Define", { fg = p.keyword })
  hl("Macro", { fg = p.accent2 })
  hl("PreCondit", { fg = p.accent2 })
  hl("Type", { fg = p.type, bold = true })
  hl("StorageClass", { fg = p.type })
  hl("Structure", { fg = p.type })
  hl("Typedef", { fg = p.type })
  hl("Special", { fg = p.accent })
  hl("SpecialChar", { fg = p.warn })
  hl("Tag", { fg = p.accent })
  hl("Delimiter", { fg = p.delimiter })
  hl("SpecialComment", { fg = p.dim, italic = true })
  hl("Debug", { fg = p.warn })
  hl("Underlined", { underline = true })
  hl("Error", { fg = p.alert, bold = true })
  hl("Todo", { fg = p.on_accent, bg = p.warn, bold = true })

  -- =========================================================================
  -- 3. Treesitter
  -- =========================================================================
  hl("@comment", { link = "Comment" })
  hl("@keyword", { link = "Keyword" })
  hl("@keyword.function", { link = "Keyword" })
  hl("@keyword.return", { fg = p.alert, bold = true }) -- Avionics: return highlighted sharply
  hl("@keyword.operator", { link = "Operator" })
  hl("@keyword.import", { link = "Include" })
  hl("@keyword.conditional", { link = "Conditional" })
  hl("@keyword.repeat", { link = "Repeat" })
  hl("@function", { link = "Function" })
  hl("@function.builtin", { fg = p.accent, bold = true })
  hl("@function.call", { link = "Function" })
  hl("@function.macro", { link = "Macro" })
  hl("@method", { link = "Function" })
  hl("@method.call", { link = "Function" })
  hl("@constructor", { fg = p.accent, bold = true })
  hl("@variable", { fg = p.fg })
  hl("@variable.builtin", { fg = p.accent2, italic = true })
  hl("@variable.parameter", { fg = p.fg_dim, italic = true })
  hl("@variable.member", { fg = p.fg })
  hl("@constant", { link = "Constant" })
  hl("@constant.builtin", { link = "Constant" })
  hl("@constant.macro", { link = "Macro" })
  hl("@string", { link = "String" })
  hl("@string.regex", { fg = p.warn })
  hl("@string.escape", { fg = p.warn, bold = true })
  hl("@character", { link = "Character" })
  hl("@number", { link = "Number" })
  hl("@boolean", { link = "Boolean" })
  hl("@type", { link = "Type" })
  hl("@type.builtin", { fg = p.type, bold = true })
  hl("@type.definition", { link = "Type" })
  hl("@type.qualifier", { link = "Type" })
  hl("@operator", { link = "Operator" })
  hl("@punctuation.delimiter", { fg = p.delimiter })
  hl("@punctuation.bracket", { fg = p.bracket })
  hl("@punctuation.special", { fg = p.accent })
  hl("@tag", { fg = p.accent })
  hl("@tag.delimiter", { fg = p.delimiter })
  hl("@tag.attribute", { fg = p.accent2 })

  -- =========================================================================
  -- 4. LSP & Diagnostics
  -- =========================================================================
  hl("DiagnosticError", { fg = p.diag_error })
  hl("DiagnosticWarn", { fg = p.diag_warn })
  hl("DiagnosticInfo", { fg = p.diag_info })
  hl("DiagnosticHint", { fg = p.diag_hint })
  hl("DiagnosticUnderlineError", { undercurl = true, sp = p.diag_error })
  hl("DiagnosticUnderlineWarn", { undercurl = true, sp = p.diag_warn })
  hl("DiagnosticUnderlineInfo", { undercurl = true, sp = p.diag_info })
  hl("DiagnosticUnderlineHint", { undercurl = true, sp = p.diag_hint })
  hl("DiagnosticVirtualTextError", { fg = p.diag_error, bg = p.bg_layer1 })
  hl("DiagnosticVirtualTextWarn", { fg = p.diag_warn, bg = p.bg_layer1 })
  hl("DiagnosticVirtualTextInfo", { fg = p.diag_info, bg = p.bg_layer1 })
  hl("DiagnosticVirtualTextHint", { fg = p.diag_hint, bg = p.bg_layer1 })
  hl("LspReferenceText", { bg = p.bg_layer2 })
  hl("LspReferenceRead", { bg = p.bg_layer2 })
  hl("LspReferenceWrite", { bg = p.bg_layer2, underline = true })

  -- =========================================================================
  -- 5. Git Signs & Diff
  -- =========================================================================
  hl("GitSignsAdd", { fg = p.git_add })
  hl("GitSignsChange", { fg = p.git_change })
  hl("GitSignsDelete", { fg = p.git_delete })
  hl("GitSignsCurrentLineBlame", { fg = p.dim, italic = true })
  hl("DiffAdd", { fg = p.git_add, bg = p.bg_layer1 })
  hl("DiffChange", { fg = p.git_change, bg = p.bg_layer1 })
  hl("DiffDelete", { fg = p.git_delete, bg = p.bg_layer1 })
  hl("DiffText", { fg = p.on_accent, bg = p.accent })

  -- =========================================================================
  -- 6. Plugins (Snacks, Telescope, Blink.cmp, WhichKey, Bufferline, Lazy)
  -- =========================================================================
  hl("SnacksPicker", { fg = p.fg, bg = p.bg_layer1 })
  hl("SnacksPickerBorder", { fg = p.line, bg = p.bg_layer1 })
  hl("SnacksPickerMatch", { fg = p.accent, bold = true })
  hl("SnacksPickerPrompt", { fg = p.accent, bold = true })
  hl("SnacksDashboardHeader", { fg = p.accent, bold = true })
  hl("SnacksDashboardKey", { fg = p.accent, bold = true })
  hl("SnacksDashboardDesc", { fg = p.fg })
  hl("SnacksDashboardIcon", { fg = p.accent })
  hl("SnacksDashboardFooter", { fg = p.dim, italic = true })

  hl("TelescopeNormal", { fg = p.fg, bg = p.bg_layer1 })
  hl("TelescopeBorder", { fg = p.line, bg = p.bg_layer1 })
  hl("TelescopeTitle", { fg = p.on_accent, bg = p.accent, bold = true })
  hl("TelescopePromptNormal", { fg = p.fg, bg = p.bg_layer2 })
  hl("TelescopePromptBorder", { fg = p.line, bg = p.bg_layer2 })
  hl("TelescopePromptPrefix", { fg = p.accent, bold = true })
  hl("TelescopeSelection", { fg = p.on_accent, bg = p.accent })
  hl("TelescopeMatching", { fg = p.warn, bold = true })

  hl("BlinkCmpMenu", { fg = p.fg, bg = p.bg_layer1 })
  hl("BlinkCmpMenuBorder", { fg = p.line, bg = p.bg_layer1 })
  hl("BlinkCmpMenuSelection", { fg = p.on_accent, bg = p.accent, bold = true })
  hl("BlinkCmpDoc", { fg = p.fg, bg = p.bg_layer2 })
  hl("BlinkCmpDocBorder", { fg = p.line, bg = p.bg_layer2 })

  hl("BufferLineFill", { bg = p.bg })
  hl("BufferLineBackground", { fg = p.dim, bg = p.bg_layer1 })
  hl("BufferLineBufferSelected", { fg = p.accent, bg = p.bg_layer2, bold = true })
  hl("BufferLineBufferVisible", { fg = p.fg, bg = p.bg_layer1 })
  hl("BufferLineSeparator", { fg = p.bg, bg = p.bg_layer1 })
  hl("BufferLineSeparatorSelected", { fg = p.bg, bg = p.bg_layer2 })
  hl("BufferLineIndicatorSelected", { fg = p.accent, bg = p.bg_layer2 })
  hl("BufferLineModified", { fg = p.warn, bg = p.bg_layer1 })
  hl("BufferLineModifiedSelected", { fg = p.warn, bg = p.bg_layer2 })

  hl("WhichKey", { fg = p.accent, bold = true })
  hl("WhichKeyGroup", { fg = p.accent2 })
  hl("WhichKeyDesc", { fg = p.fg })
  hl("WhichKeySeparator", { fg = p.dim })
  hl("WhichKeyBorder", { fg = p.line, bg = p.bg_layer1 })
  hl("WhichKeyNormal", { bg = p.bg_layer1 })

  hl("LazyNormal", { bg = p.bg_layer1 })
  hl("LazyBorder", { fg = p.line, bg = p.bg_layer1 })
  hl("MasonNormal", { bg = p.bg_layer1 })
  hl("MasonBorder", { fg = p.line, bg = p.bg_layer1 })
end

return M
